# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('proyectos.views',
                       url(r'^$',
                           'resultados',
                           name='resultados'),
                       url(r'^(?P<rubro_id>\d+)/$',
                           'resultados',
                           name='resultados'),
                       url(r'^rubro/(?P<slug_rubro>[\w]+)/$',
                           'rubro',
                           name='rubro'),
                       url(r'^desarrollado/(?P<slug>[\w]+)/$',
                           'perfil_desarrollado',
                           name='perfil_desarrrollado'),
                       url(r'^venta_terreno/$',
                           'venta_terreno',
                           name='venta_terreno'),
                       url(r'^fotos/(?P<proyecto_id>\d+)/$',
                           'fotos',
                           name='slider_fotos'),
                       url(r'^videos/(?P<proyecto_id>\d+)/$',
                           'videos',
                           name='slider_videos'),
                       url(r'^planos/(?P<plano_id>\d+)/$',
                           'planos',
                           name='proyectos_planos'),
                       url(r'^planos_slider/(?P<proyecto_id>\d+)/$',
                           'planos_slider',
                           name='proyectos_planos_slider'),
                       url(r'^get_item_data/$',
                           'ajax_get_item_data',
                           name='proyectos_ajax_get_item_data'),
                       url(r'^solicitud/(?P<item_id>\d+)?$',
                           'solicitud',
                           name='proyectos_solicitud'),
                       # url(r'^solicitud_enviada/$',
                       #     TemplateView.as_view(template_name='proyectos/solicitud_enviada.html'),
                       #     name='proyectos_solicitud_enviada'),
                       url(r'^plano_item/(?P<item_id>\d+)?$',
                           'plano_item',
                           name='proyectos_plano_item'),
                       url(r'^solicitud_enviada/(?P<item_id>\d+)/$',
                           'solicitud_enviada',
                           name='proyectos_solicitud_enviada'),
                       url(r'^items_proyecto/(?P<proyecto_id>\d+)/$',
                           'items_proyecto',
                           name='items_proyecto'),
                       url(r'^json_suscribir/$',
                           'json_suscribir',
                           name='json_suscribir'),
                       url(r'^json_desuscribir/$',
                           'json_desuscribir',
                           name='json_desuscribir'),
                       url(r'^json_afiliar/$',
                           'json_afiliar',
                           name='json_afiliar'),
                       url(r'^json_desafiliar/$',
                           'json_desafiliar',
                           name='json_desafiliar'),
                       url(r'^json_proyectos_slider/$',
                           'json_proyectos_slider',
                           name='json_proyectos_slider'),
                       url(r'^json_fast_proyectos/$',
                           'json_fast_proyectos',
                           name='json_fast_proyectos'),
)
