# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url
from usuarios.forms import RecuperarPassForm

urlpatterns = patterns('usuarios.views',
    url(r'^$',
        'perfil_privado_usuario',
        name='perfil_privado_usuario'),
    url(r'^registro_corredor/$',
        'registro_corredor',
        name='registro_corredor'),
    url(r'^registro/$',
        'registro',
        name='registro'),
    url(r'^iframes/editar_usuario/$',
        'usuario_editar',
        name='usuario_editar'),
    url(r'^iframes/cambiar_password/$',
        'usuario_cambiar_password',
        name='usuario_cambiar_password'),
    url(r'^iframes/editar_intereses/$',
        'usuario_intereses',
        name='usuario_intereses'),
    url(r'^iframes/editar_subscripciones/$',
        'usuario_subscripciones',
        name='usuario_subscripciones'),
    url(r'^iframes/editar_separados/$',
        'usuario_separados',
        name='usuario_separados'),
    url(r'^iframes/login/$',
        'log_in',
        name="login"),
    url(r'^iframes/recuperar_pass/$',
        'simple_form',
        {"Form": RecuperarPassForm,
         "template": 'usuarios/iframes/recuperar_pass.html'},
        name="recuperar_pass"),
    url(r'^cambio_password/(?P<clave_activacion>[\w]+)/(?P<password>[\w]+)/$',
        'cambio_password', name='cambio_password'),
    url(r'^logout/$',
        'log_out',
        name='logout'),
    url(r'^verificar/(?P<clave_activacion>[\w]+)/$',
        'verificar',
        name="verificar"),
    url(r'^channel/$',
        'fb_channel',
        name='fb_channel'),
    url(r'^json_registro/$',
        'json_registro',
        name='json_registro'),
    url(r'^json_cancelar_solicitud/$',
        'json_cancelar_solicitud',
        name='json_cancelar_solicitud'),
)

urlpatterns += patterns("",
    url(r'^ayuda_clientes/$',
        'common.chat_server.ayuda_clientes',
        name='ayuda_clientes'),
)
